---
kind: pkgfile.Build
spec:
  targets:
    - sbc-riscv64
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/pl4nty
      - name: PKGS
        defaultValue: latest
      - name: TOOLS_PREFIX
        defaultValue: ghcr.io/pl4nty
      - name: TOOLS
        defaultValue: latest
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - u-boot/u-boot
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
