---
kind: pkgfile.Build
spec:
  targets:
    - sbc-riscv64
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/pl4nty
      - name: PKGS
        defaultValue: latest
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
