---
kind: pkgfile.Build
spec:
  targets:
    - sbc-riscv64
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
    - TOOLS_PREFIX
    - TOOLS
  makefile:
    extraVariables:
      - name: TAG_SUFFIX
      - name: TAG_SUFFIX_IN
        defaultValue: $(TAG_SUFFIX)
      - name: IMAGE_TAG_IN
        defaultValue: $(TAG)$(TAG_SUFFIX_IN)
      - name: IMAGER_ARGS
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - u-boot/u-boot
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
